//<auto-generated/>
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Forms;

namespace Szt2
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App : System.Windows.Application
    {
        /// <summary>
        /// Checks how many screens are in use when the program starts up and decide where to open windows.
        /// </summary>
        /// <param name="e">The start up event.</param>
        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);

            MainWindow mainWindow = new MainWindow();

            if (System.Windows.Forms.Screen.AllScreens.Length > 1)
            {
                Screen s2 = Screen.AllScreens[0];
                mainWindow.Width = s2.WorkingArea.Width;
                mainWindow.Height = s2.WorkingArea.Height;
                mainWindow.Top = s2.WorkingArea.Location.Y;
                mainWindow.Left = s2.WorkingArea.Location.X;
            }
            else
            {
                Screen s2 = Screen.AllScreens[0];
                mainWindow.Width = s2.WorkingArea.Width;
                mainWindow.Height = s2.WorkingArea.Height;
                mainWindow.Top = s2.WorkingArea.Location.Y;
                mainWindow.Left = s2.WorkingArea.Location.X;
            }

            mainWindow.Show();
        }
    }
}
