IF OBJECT_ID('ORDERLISTITEM', 'U') IS NOT NULL DROP TABLE ORDERLISTITEM;
IF OBJECT_ID('PRODUCT', 'U') IS NOT NULL DROP TABLE PRODUCT;
IF OBJECT_ID('CATEGORY', 'U') IS NOT NULL DROP TABLE CATEGORY;
IF OBJECT_ID('ORDERS', 'U') IS NOT NULL DROP TABLE ORDERS;

CREATE TABLE CATEGORY 
    (CATEGORYID NUMERIC(3) NOT NULL IDENTITY(1,1),
	 CNAME              NVARCHAR(20) NOT NULL,
     PICTURE               NVARCHAR(100),
  CONSTRAINT CATEGORY_PRIMARY_KEY PRIMARY KEY (CATEGORYID));

CREATE TABLE PRODUCT 
    (PRODUCTID	NUMERIC(3) NOT NULL IDENTITY(1,1),
	 PNAME              NVARCHAR(20) NOT NULL,
     PICTURE               NVARCHAR(100),
	 UNITPRICE			NUMERIC(5) NOT NULL,
	 PCATEGORY			NUMERIC(3) NOT NULL,
  CONSTRAINT PRODUCT_PRIMARY_KEY PRIMARY KEY (PRODUCTID),
  CONSTRAINT PRODUCT_CATEGORY_FK1 FOREIGN KEY (PCATEGORY) REFERENCES CATEGORY (CATEGORYID));

  CREATE TABLE ORDERS
	(ORDERID NUMERIC(3) NOT NULL IDENTITY(1,1),
	 ORDERDATE DATE NOT NULL,
	 TOTALPRICE NUMERIC(6),
	 RATING NUMERIC(3)
	CONSTRAINT ORDERS_PRIMARY_KEY PRIMARY KEY (ORDERID));

CREATE TABLE ORDERLISTITEM
	(ORDERLISTITEMID NUMERIC(3) NOT NULL IDENTITY(1,1),
	 SUBTOTAL NUMERIC(6),
	 AMOUNT NUMERIC(3),
	 PRODUCT NUMERIC(3),
	 ORDERID NUMERIC(3),
	CONSTRAINT ORDERLISTITEM_PRIMARY_KEY PRIMARY KEY (ORDERLISTITEMID),
	CONSTRAINT PRODUCT_ORDERLISTITEM_FK1 FOREIGN KEY (PRODUCT) REFERENCES PRODUCT (PRODUCTID),
	CONSTRAINT ORDER_ORDERLISTITEM_FK1 FOREIGN KEY (ORDERID) REFERENCES ORDERS (ORDERID));